#Configuração do banco PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/parimparjob
    username: postgres
    password: postgres
  batch:
    jdbc:
      initialize-schema: always
